home: الرئيسية
welcome: أهلا بك
world: عالم
community: المجتمع
dismiss: تجاهل
description: الوصف
title: عنوان
new: جديد
username: اسم المستخدم
goto.account: اذهب الى تفاصيل الحساب
join.worldanvil.cta: انظم إلى نقابة صانعي العوالم
join.discord.description: شارك في تطوير World Anvil - إنظم إلي تحديات بناء العوالم
  - اربح جوائز وشارات رائعة!
join.discord: انظم إلى ال Discord الخاص بنا.
identifier: المُعرف
reference: مرجع علامات التصميم
help: هل تحتاج لمساعدة؟
weight: وزن
status: الحالة
state: حالة
goto.articles.list: اذهب الى قائمة المقالات
world.designer: لوحة تصميم العالم
private.club: نادٍ خاص. أعضاء النقابة فقط
allies: الحلفاء والشركاء بالجريمة
studio.description.header: ما هو استوديو المُنشئ
studio.templates: 'استوديو المُنشىء: قوالب المقالات'
studio.sheets: 'استوديو المُنشئ: جداول البيانات'
studio.homepage: الصفحة الرئيسية لاستوديو المنشئ
studio.description.text: "استوديو المُنشئئ هو موطِن كُل الخصائص المُتقدمة في World\
  \ Anvil. الخبراء (عضوية مدفوعة) وما فوقهُم، سيتمكنون من إنشاء ومُشاركة أوراق الشخصيات،\
  \ أدوات، علامات الخرائط المُخصصة والمزيد كُلما نمَونا."
studio.pins: 'استوديو المُنشئين : ثبت'
advanced_options: افتح الأدوات والخيارات المتقدمة
guild.required.master: تتطلب هذه الميزة عضوية الخبير وأعلاها في النقابة.
guild.required: تتطلب هذه الميزة عضوية النقابة!
guild.required.grandmaster: تتطلب هذه الميزة عضوية العظيم في نقابة وما فوق.
todo.your.list: 'قائمة المهام'
todo.status.one: أُنشئ المقال، ما زال قيد العمل ولم يتم نشرُه
todo.status.zero: انقر على العنوان لإنشاء مقالة!
todo.status.two: نُشر المقال وما زال قيد العمل
todo.status.three: انتهى المقال!
notes: ملحوظات
theme: الطابع
article.template: قالب المقال
views: المشاهدات
open: افتح
private: خاص
public: عام
visibility: الرؤية
update.date: تاريخ آخر تحديث
publication.date: تاريخ النشر
creation.date: 'تاريخ الإنشاء '
author: مؤلف
category: الفئة
favorites: المُفضلات
author.notes: ملحوظات المؤلف
notifications: 'الاشعارات '
comments: التعليقات
access.homepage: الانتقال للصفحة الرئيسية
access.description: نحنُ نعتذر لكن لا يُمكنك الوصول الى هذه الصفحة. هذا على الارجع
  لأن المقالة خاصة وليس لديك الحق لرؤيتها.
