home: الرئيسية
welcome: أهلا بك
world: العالم
community: المجتمع
dismiss: تجاهل
description: الوصف
title: عنوان
new: جديد
username: اسم المستخدم
goto.account: اذهب الى تفاصيل الحساب
join.worldanvil.cta: انظم إلى نقابة صانعي العوالم
join.discord.description: شارك في تطوير World Anvil - إنظم إلي تحديات بناء العوالم
  - اربح جوائز وشارات رائعة!
join.discord: انظم إلى ال Discord الخاص بنا.
identifier: المُعرف
reference: مرجع علامات التصميم
help: هل تحتاج لمساعدة؟
weight: الوزن
status: الحالة
state: حالة
goto.articles.list: اذهب الى قائمة المقالات
world.designer: لوحة تصميم العالم
private.club: نادٍ خاص. أعضاء النقابة فقط
allies: الحلفاء والشركاء بالجريمة
studio.description.header: ما هو استوديو المُنشئ
studio.templates: 'استوديو المُنشىء: قوالب المقالات'
studio.sheets: 'استوديو المُنشئ: جداول البيانات'
studio.homepage: الصفحة الرئيسية لاستوديو المنشئ
studio.description.text: "استوديو المُنشئئ هو موطِن كُل الخصائص المُتقدمة في World\
  \ Anvil. الخبراء (عضوية مدفوعة) وما فوقهُم، سيتمكنون من إنشاء ومُشاركة جداول الشخصيات،\
  \ أدوات، علامات الخرائط المُخصصة والمزيد كُلما نمَونا."
studio.pins: 'استوديو المُنشئين : المثبت'
advanced_options: افتح الأدوات والخيارات المتقدمة
guild.required.master: تتطلب هذه الميزة عضوية الخبير وأعلاها في النقابة.
guild.required: تتطلب هذه الميزة عضوية النقابة!
guild.required.grandmaster: تتطلب هذه الميزة عضوية العظيم في نقابة وما فوق.
todo.your.list: 'قائمة المهام'
todo.status.one: أُنشئ المقال، ما زال قيد العمل ولم يتم نشرُه
todo.status.zero: انقر على العنوان لإنشاء مقالة!
todo.status.two: نُشر المقال وما زال قيد العمل
todo.status.three: انتهى المقال!
notes: ملحوظات
theme: الطابع
article.template: قالب المقال
views: المشاهدات
open: افتح
private: خاص
public: عام
visibility: الرؤية
update.date: تاريخ آخر تحديث
publication.date: تاريخ النشر
creation.date: 'تاريخ الإنشاء'
author: المؤلف
category: الفئة
favorites: المُفضلات
author.notes: ملحوظات المؤلف
notifications: 'الاشعارات '
comments: التعليقات
access.homepage: اذهب للصفحة الرئيسية
access.description: نحنُ نعتذر لكن لا يُمكنك الوصول الى هذه الصفحة. هذا على الارجع
  لأن المقالة خاصة وليس لديك الحق لرؤيتها.
access.activate.subscription: تفعيل الاشتراك
access.activate.description: اكتُب رمز الاشتراك الخاص بك أدناه للوصل للمُحتوى. إنهُ
  بهذه البساطة!
access.activate: تفعيل الإشتراك
access.passcode.description: هذهِ الصفحة محمية بكلمة مرور! إن كُنت تملك كلمة المرور
  رجاءً ضعها أدناه للوصول للمُحتوى.
access.passcode: كلمة المرور مطلوبة
wip: 'العمل قيد التنفيذ'
access.activate.login: تحتاج إلى تسجيل الدخول لتفعيل إشتراكك!
access.activate.code: أدخل رمز التفعيل
access.return: عُد من حيثُ أتيت!
access.multipass: متعدد؟
dashboard.page.title: لوحة التحكم العالمية الخاصة بك
dashboard.features.mistake: 'هل قمت بتنشيط ميزات بناء العالم عن طريق الخطأ؟'
dashboard.create.first: أنشئ عالمك الأول!
dashboard.news: الأخبار
dashboard.manage.features: إدارة ميزاتك النشطة
dashboard.campaigns: أحداثك
dashboard.characters: شخصياتك
dashboard.worlds: عوالمك
dashboard.events: الأحداث
