community: Community
username: Username
welcome: Welcome
new: 'new'
title: Title
description: Description
state: State
status: Status
weight: Weight 
help: Do you need Help?
reference: Design Tags Reference
advanced_options: Open Advanced Tools & Options
home: Home
class: CSS Class
class.name: CSS Class Name
identifier: Identifier
dismiss: Dismiss
upcoming.streams: 'Upcoming Streams'
join.discord: Join our Discord
join.discord.description: Take part on the development of World Anvil - join world building challenges - win prizes and awesome badges!
join.worldanvil.cta: Join the Worldbuilders Guild

goto.account: Go to Account details
goto.articles.list: Go to Articles List

allies: Allies & Partners in Crime
private.club: Private club. Guild Members only

world.designer: World Designer Panel # Title of authoring Tool
meta.title.standard: Worldbuilding and RPG Campaign Management | World Anvil 
meta.description.standard: Worldbuilding and RPG Campaign Management tools for all Storytellers, Dungeon Masters and fiction Authors

studio.homepage: Creator's Studio Homepage
studio.pins: "Creator's Studio: Pins"
studio.sheets: "Creator's Studio: Sheets"
studio.templates: "Creator's Studio: Article Templates"
studio.description.header: What's the Creator's Studio
studio.description.text: The Creator's studio is the home of all advanced customization in World Anvil. Grandmasters, and above, will be able to create and share Character sheets, Widgets, Custom Map Markers and much more as we grow.

guild.required: This feature requires a Guild Membership!
guild.required.master: This feature requres a Guild Membership of Master and above.
guild.required.grandmaster: This feature requires a Guild Membership of Grandmaster and above.


todo.your.list: To-Do List
todo.status.zero: Click on the title to Create the Article!
todo.status.one: The article is created, Unpublished and still Work in Progress
todo.status.two: The article is Published and still Work in Progress
todo.status.three: The article is Finished!

notes: Notes 
moderation: Moderation
metadata: Metadata
tags: Tags 
theme: Theme
article.template: Article template
world: World
category: Category
author: Author
creation.date: Creation Date
publication.date: Publication Date
update.date: Last Update Date 
visibility: Visibility 
public: Public 
private: Private 
open: Open 
views: Views 
favorites: Favorites 
comments: Comments
notifications: 'Notifications'
wip: Work In Progress
author.notes: Author's Notes


access.multipass: Multipass?
access.description: I am so sorry but you don't have access to this page. This is most probably because the article is private and you don't have the necessary rights to view it.
access.return: Head back where you came from!
access.homepage: Go to Homepage
access.passcode: Password Required
access.passcode.description: This page is protected by a password! If you have the password please enter it below to access the content.
access.activate: Subscription Activation
access.activate.description: Write your Subscription code below to get access to the content. It's that simple!
access.activate.subscription: Activate Subscription
access.activate.code: Enter Activation Code
access.activate.login: You will need to be logged in to activate your subscription!

dashboard.page.title: Your Global Dashboard
dashboard.create.first: Create your first World!
dashboad.cta: GET WORLDBUILDING
dashboard.features.mistake: Have you activated worldbuilding features by mistake?
dashboard.manage.features: Manage your activated features
dashboard.news: News
dashboard.events: Events
dashboard.worlds: Your Worlds
dashboard.characters: Your Characters
dashboard.campaigns: Your Campaigns
dashboard.world.memberships: World Memberships
dashboard.dev.updates: Development Updates
dashboard.in.news: In the News
dashboard.videos: Recent Videos
dashboard.stream: Upcoming Streams
dashboard.podcast.cta: Listen to our Worldbuilding Podcast
dashboard.worldbuilding.disabled: The worldbuilding features are disabled
dashboard.continue: Continue Building
dashboard.recent.articles: Your Recently articles
dashboard.worlds.max: You have reached the maximum number of Worlds
dashboard.help.grow: Help us keep World Anvil alive and growing!
dashboard.followed.worlds: Your Followed Worlds
dashboard.followed.characters: Followed Characters
dashboard.upcoming.sessions: Upcoming Sessions
dashboard.upcoming.stream: Upcoming Streams & Events