new: oznámení
help: Potřebuješ pomoc?
home: Domů
world.designer: Panel tvůrce světa
description: Popis
status: Stav
meta.title.standard: Správa tvoření světů a RPG kampaní | World Anvil
title: Název
weight: Důležitost
allies: Komplicové
private.club: Soukromý klub. Pouze pro členy Cechu tvůrců světů (WBG)
meta.description.standard: Nástroje správy pro světů a RPG kampaní pro všechny vypravěče,
  pány jeskyně a spisovatele
class: CSS Třídy
class.name: Název CSS třídy
studio.homepage: Domovská stránka Tvůrčí dílny
studio.description.header: Co je Tvůrčí dílna
studio.description.text: Tvůrčí dílna je místem pro pokročilé přizpůsobení stránek
  World Anvil. Velmistři a výše postavení budou moci vytvářet a sdílet osobní deníky,
  widgety, vlastní značky pro mapy a mnohem více.
public: Veřejné
private: Soukromé
guild.required: Tato možnost vyžaduje Členství v cechu!
guild.required.master: Tato možnost vyžaduje Členství v cechu s úrovní Mistr a vyšší.
guild.required.grandmaster: Tato možnost vyžaduje Členství v cechu s úrovní Velmistr
  a vyšší.
todo.your.list: Úkoly
todo.status.two: Článek je zveřejněn a stále je ve vývoji (WIP)
todo.status.three: Článek je dokončen!
notes: Poznámky
metadata: Metadata
tags: Štítky
article.template: Šablona článku
world: Svět
category: Kategorie
author: Autor
creation.date: Datum vytvoření
update.date: Datum poslední úpravy
visibility: Viditelnost
open: Otevřené
views: Zobrazení
favorites: Oblíbené
comments: Komentáře
wip: Stále ve vývoji (WIP)
access.description: Je nám líto ale k této stránce nemáš přístup. Článek je nejspíš
  soukromý a Ty nemáš dostatečná oprávnění k jeho zobrazení.
access.return: Vrať se, odkud jsi přišel!
access.homepage: Přejít na domovskou stránku
todo.status.zero: Kliknutím na název vytvoříš článek!
todo.status.one: Článek byl vytvořen, nezveřejněn a je stále ve vývoji (WIP)
moderation: Moderace
author.notes: Poznámky autora
access.multipass: Multipas?
username: Uživatelské jméno
state: Stát
access.activate.code: Vlož aktivační klíč
identifier: Identifikátor
studio.templates: 'Tvůrčí dílna: Šablony článků'
studio.pins: 'Tvůrčí dílna: Piny'
studio.sheets: 'Tvůrčí dílna: Složky'
theme: Schéma
publication.date: Datum publikace
access.passcode: Požadováno heslo
access.passcode.description: Tato stránka je chráněna heslem! Pokud máte heslo, zadejte
  ho níže k přístupu k obsahu.
access.activate: Aktivace odběru
access.activate.description: Níže zadej kód odběru pro přístup k obsahu. Je to tak
  jednoduché!
access.activate.subscription: Aktivuj odběr
access.activate.login: Musíš být přihlášen, abys ses mohl stát odběratelem!
dashboard.upcoming.stream: Nadcházející streamy a události
dashboard.upcoming.sessions: Nadcházející sezení
dashboard.followed.characters: Postavy, které sleduješ
dashboard.followed.worlds: Světy, které sleduješ
dashboard.help.grow: Pomoz nám držet World Anvil na živu a rostoucí!
dashboard.worlds.max: Dosáhl jsi maximálního povoleného počtu světů
dashboard.recent.articles: Tvoje poslední články
dashboard.continue: Pokračuj v budování
dashboard.worldbuilding.disabled: Funkce pro budování světa jsou zakázány
dashboard.podcast.cta: Poslouchej náš podcast
dashboard.videos: Poslední videa
dashboard.in.news: V novinkách
dashboard.dev.updates: Aktualizace vývoje
dashboard.communities: Tvoje komunity
dashboard.campaigns: Tvoje kampaně
dashboard.characters: Tvoje postavy
dashboard.worlds: Tvoje světy
dashboard.events: Události
dashboard.news: Novinky
dashboard.manage.features: Spravujte své aktivní funkce
dashboard.features.mistake: Aktivoval jsi funkce budování světa omylem ?
dashboad.cta: ZAČNI TVOŘIT
dashboard.create.first: Vytvoř svůj první svět!
dashboard.page.title: Tvoje nástěnka
goto.articles.list: Jdi k seznamu článků
goto.account: Jdi k detailům účtu
join.worldanvil.cta: Přidej se k cechu Světotvůrců
join.discord.description: Zúčastni se vývoje World Anvil - připoj se k výzvám v budování
  světů - získej odměny a úžasné odznaky!
join.discord: Přidej se na náš Discord
upcoming.streams: Nadcházející streamy
dismiss: Zahodit
welcome: Vítej
community: Komunita
notifications: Upozornění
dashboard.stream: Nadcházející vysílání
