new: Neu
title: Titel
status: Status
help: Hilfe
home: Home
allies: Verbündete & Komplizen
meta.title.standard: Worldbuilding- und RPG Kampagnen-Verwaltung | World Anvil
meta.description.standard: Worldbuilding und RPG Kampagnen-Management-Tools für alle
  Geschichtenerzähler, Dungeon Master und Autoren
world.designer: Weltenschmied-Panel
description: Beschreibung
weight: Gewichtung
private.club: Geschlossene Gesellschaft. Nur für Gildenmitglieder.
class: CSS Klasse
class.name: CSS Klassenname
studio.homepage: Homepage des 'Creators Studio'
studio.description.header: Was ist das 'Creators Studio'?
studio.description.text: Das Creators Studio ist der Ort für alle fortgeschrittenen
  Individualisierungen in World Anvil. Großmeister und höher können hier Charakterbögen,
  Widgets, benutzerdefinierte Karten Markierungen und in der Zukunft noch viel mehr
  erstellen und untereinander teilen.
guild.required: Dieses Feature bedarf einer Gildenmitgliedschaft!
guild.required.master: Dieses Feature bedarf einer Gildenmitgliedschaft als Master
  oder höher.
guild.required.grandmaster: Dieses Feature bedarf einer Gildenmitgliedschaft als Grandmaster
  oder höher.
todo.your.list: To-Do Liste
todo.status.zero: Klicke auf den Titel um einen Artikel zu erzeugen.
todo.status.one: Der Artikel wurde erzeugt, ist noch nicht veröffentlicht und noch
  in Arbeit
todo.status.two: Der Artikel wurde veröffentlicht und ist noch in Arbeit
todo.status.three: Der Artikel ist fertig!
notes: Notizen
moderation: Moderation
metadata: Metadaten
tags: Tags
article.template: Artikel-Template
world: Welt
category: Kategorie
author: Autor
update.date: Letztes Änderungsdatum
visibility: Sichtbarkeit
creation.date: Erstellungsdatum
public: Öffentlich
private: Privat
open: Offen
views: Ansichten
favorites: Favoriten
comments: Kommentare
wip: In Arbeit
access.multipass: Multipass?
access.description: Es tut uns Leid, aber leider hast du keinen Zugang zu dieser Seite.
  Das liegt wahrscheinlich daran, dass der Artikel privat ist und du nicht die notwendigen
  Rechte hast, um ihn zu sehen.
access.return: Zurück dahin, wo du herkamst!
access.homepage: Gehe zur Startseite
author.notes: Anmerkungen des Autors
username: Benutzername
state: Zustand
studio.pins: 'Creators Studio: Pins'
studio.sheets: 'Creator''s Studio: Charakterbögen'
access.passcode: Passwort benötigt
access.passcode.description: Diese Seite ist passwortgeschützt! Wenn du das Passwort
  kennst, gib es bitte ein, um die Seite zu sehen.
access.activate.description: Gib deinen Abonnentencode ein, um Zugriff auf die Seite
  zu erhalten. So einfach ist das!
access.activate.subscription: Abonnement aktivieren
access.activate.code: Aktivierungscode eingeben
access.activate.login: Du musst eingeloggt sein, um dein Abonnement zu aktivieren!
access.activate: Abonnement Aktivierung
