new: nowe
title: Tytuł
status: Status
help: Pomoc
home: Strona Główna
allies: Sprzymierzeńcy i Wspólnicy
world.designer: Panel Projektanta Światów
meta.title.standard: Światotwórstwo i zarządzanie kampaniami RPG | World Anvil
meta.description.standard: Światotwórstwo i zarządzanie kampaniami RPG dla wszystkich
  Mistrzów Gry i autorów fantasy
description: Opis
weight: Waga
private.club: Tylko dla Członków Gildii
class: Klasa CSS
class.name: Nazwa Klasy CSS
studio.homepage: Strona główna Studia Twórców
studio.description.header: Czym jest Studio Twórców
studio.description.text: Studio Twórców to miejsce, w którym odbywa się wszelka personalizacja
  World Anvil. Członkowie o randze Wielkiego Mistrza lub wyższej są w stanie tworzyć
  i udostępniać Karty postaci, Widżety, Własne Znaczniki Map, a wraz z rozwojem strony
  jeszcze więcej!
world: Świat
category: Kategoria
author: Autor
guild.required: Ta opcja wymaga członkostwa w Gildii!
guild.required.master: Ta opcja wymaga członkostwa w Gildii na poziomie od Mistrza
  wzwyż.
guild.required.grandmaster: Ta opcja wymaga członkostwa w Gildii, od poziomu Wielkiego
  Mistrza wzwyż.
todo.your.list: Lista "Do Zrobienia"
todo.status.zero: Kliknij na tytuł by stworzyć artykuł!
todo.status.one: Ten artykuł jest tworzony, nieopublikowany i praca nad nim nadal
  trwa.
todo.status.two: Ten artykuł został opublikowany, ale praca nad nim nadal trwa.
article.template: Szablon artykułu
creation.date: Data utworzenia
update.date: Data ostatniej modyfikacji
todo.status.three: Ten artykuł został ukończony!
metadata: Metadane
visibility: Widoczność
public: Publiczne
private: Prywatne
open: Otwórz
views: Wyświetlenia
notes: Notatki
moderation: Zmiana
tags: Tagi
access.multipass: Multipass?
access.description: Niestety nie masz dostępu do tej strony. Prawdopodobnie artykuł
  jest prywatny, a ty nie masz odpowiednich uprawnień, aby go zobaczyć.
access.return: Wróć skąd przyszedłeś!
access.homepage: Wróć do strony głównej
favorites: Ulubione
comments: Komentarze
wip: Praca w toku
author.notes: Notatki autora
username: Nazwa Użytkownika
state: Stan
studio.pins: 'Studio Twórców: Pinezki'
studio.sheets: 'Studio Twórców: Karty'
access.passcode: Wymagane Hasło
access.passcode.description: Ta strona jest zabezpieczona hasłem! Wpisz je poniżej,
  aby uzyskać dostęp to treści.
access.activate: Aktywacja Subskrypcji
access.activate.description: Poniżej podaj swój kod Subskrypcji, aby uzyskać dostęp
  do zawartości. To takie proste!
access.activate.subscription: Aktywuj Subskrypcję
access.activate.code: Wpisz kod aktywacyjny
access.activate.login: Musisz być zalogowany, aby aktywować subskrypcję!
notifications: Powiadomienia
welcome: Witaj
community: Społeczność
dismiss: Odrzuć
