new: Új
title: Cím
description: Leírás
status: Állapot
weight: Súly
help: Kell segítség?
home: Kezdőlap
allies: Szövetségesek, Bűntársak
private.club: Privát klub. Csak Céhtagoknak
world.designer: Világtervező Lap
meta.title.standard: Világalkotás és RPG Kampányvezetés | World Anvil
meta.description.standard: Világalkotói, és RPG Kampányvezetői eszközök minden Mesélőnek,
  Kalandmesternek, és Szerzőnek
class: CSS Osztály
class.name: CSS Osztály Neve
studio.homepage: Alkotók Stúdiója Kezdőlap
studio.description.header: Mi az Alkotók Stúdiója
studio.description.text: Az Alkotók Stúdiója nyújt otthont a World Anvil minden fejlettebb
  testreszabási lehetőségnek. Nagymestereknek, és mindenkinek fölötte lehetősége van
  Karakterlapok, Widgetek, Egyedi Térkép Jelzők, és miegymás létrehozására, és megosztására,
  ahogy növekszünk.
guild.required: Ehhez a funkcióhoz Céhtagnak kell lenned!
guild.required.master: Ehhez a funkcióhoz legalább Mester rangú Céhtagnak kell lenned.
guild.required.grandmaster: Ehhez a funkcióhoz legalább Nagymester rangú Céhtagnak
  kell lenned.
todo.your.list: Teendők
todo.status.zero: Kattints a címre hogy Létrehozd a Bejegyzést!
todo.status.one: A bejegyzés létrehozva, Publikálatlan, és még mindig Átdolgozás Alatt
  áll
todo.status.two: A bejegyzés publikálva, és még mindig Átdolgozás Alatt áll
todo.status.three: A bejegyzés befejezve!
notes: Jegyzetek
moderation: Moderáció
metadata: Metaadatok
tags: Címkék
article.template: Bejegyzés sablon
world: Világ
category: Kategória
author: Szerző
creation.date: Létrehozás Dátuma
update.date: Legutolsó Frissítés Dátuma
visibility: Láthatóság
public: Nyilvános
private: Privát
open: Nyílt
views: Megtekintések
favorites: Kedvencek
comments: Megjegyzések
wip: Átdolgozás Alatt
access.multipass: Világjegy?
access.description: Sajnáljuk, de nincs engedélyed megnyitni ezt az oldalt. Ez valószínűleg
  azért van, mert az oldal privát, és nem rendelkezel a megfelelő jogokkal hogy megtekintsd.
access.return: Térj vissza ahonnét jöttél!
access.homepage: A Kezdőoldalra
author.notes: A Szerző Jegyzetei
studio.pins: 'Alkotók Stúdiója: Kitűzések'
studio.sheets: 'Alkotók Stúdiója: Lapok'
access.passcode: Jelszó Szükséges
access.passcode.description: Ez az oldal jelszóval védett! Ha rendelkezel a jelszóval,
  add meg alul, hogy hozzáférj a tartalomhoz.
username: Felhasználónév
state: Állam
access.activate: Feliratkozás Aktiválása
access.activate.description: Írd be alulra a Feliratkozási kódod, hogy hozzáférj a
  tartalomhoz. Ennyire egyszerű!
access.activate.subscription: Feliratkozás Aktiválása
access.activate.code: Aktiváló Kód Megadása
access.activate.login: Be kell jelentkezned a Feliratkozásod aktiválásához!
identifier: Azonosító
studio.templates: 'Alkotók Stúdiója: Bejegyzés Sablonok'
theme: Téma
publication.date: Kiadás Dátuma
dashboard.upcoming.stream: Közelgő Stream-ek & Események
dashboard.upcoming.sessions: Közelgő Ülések
dashboard.followed.characters: Követett Karakterek
dashboard.followed.worlds: Követett Világaid
dashboard.help.grow: Segíts a World Anvil-nak élni és nőni !
dashboard.worlds.max: Elérted a világok maximum számát
dashboard.recent.articles: Az Újabb Bejegyzéseid
dashboard.continue: Építés folytatása
dashboard.worldbuilding.disabled: A világépítő funkciók kikapcsolva
dashboard.podcast.cta: Halgass bele a Világépítő Podcast-ünkbe
dashboard.videos: Friss videók
dashboard.in.news: A hírekben
dashboard.dev.updates: Fejlesztési hírek
dashboard.communities: Közösségeid
dashboard.campaigns: Kampányaid
dashboard.characters: Karaktereid
dashboard.worlds: Világaid
dashboard.events: Események
dashboard.news: Hírek
dashboard.manage.features: Kezeld az aktivált funkciókat
dashboard.features.mistake: Tán véletlenül aktiváltad a világépítő funkciókat?
dashboad.cta: ÉPÍTS VILÁGOT
dashboard.create.first: Hozd Létre az első Világod!
dashboard.page.title: A Globális Irányítópultod
goto.articles.list: A Bejegyzéslistához
goto.account: A Fiókadatokhoz
join.worldanvil.cta: Csatlakozz a Világépítők Céhébe
join.discord.description: Végy részt a World Anvil fejlesztésében -nevezz világépítő
  versenyekre- nyerj díjakat, és király kitűzőket!
join.discord: Csatlakozz Discord-unkhoz
upcoming.streams: Közelgő Stream-ek
dismiss: Elutasítás
welcome: Üdvözöljük
community: Közösség
dashboard.stream: Közelgő Stream-ek
dashboard.world.memberships: Világtagság
notifications: Értesítések
advanced_options: További eszközök & opciók megnyitása
reference: Dizájncímke Referencia
