username: Nome Utente
status: Status
weight: Peso
help: Aiuto
home: Home
new: nuovo
title: Titolo
description: Descrizione
class: Classe CSS
class.name: Nome della Classe CSS
allies: Alleati e Complici
private.club: Club privato. Solo Membri della Gilda
world.designer: Pannello di Progettazione Mondo
meta.title.standard: Creazione di Mondi e Gestione di Campagne GDR | World Anvil
meta.description.standard: Strumenti per la creazione di mondi e la gestione di campagne
  GDR per tutti i Narratori, Dungeon Master e Scrittori di fiction
studio.homepage: Homepage del Laboratorio
studio.pins: 'Laboratorio: Marcatori'
studio.sheets: 'Laboratorio: Schede'
studio.description.header: Che cos'è il Laboratorio
studio.description.text: Il Laboratorio è la casa di tutte le personalizzazioni avanzate
  su World Anvil. I Granmaestri, e superiori, potranno creare e condividere Schede
  personaggio, Widgets, Marcatori di Mappe Personalizzati e molto altro quando cresceremo.
guild.required: Questa funzione richiede l'iscrizione alla Gilda!
guild.required.master: Questa funzione richiede l'iscrizione alla Gilda con il rango
  di Maestro o superiore.
guild.required.grandmaster: Questa funzione richiede l'iscrizione alla Gilda con il
  rango di Granmaestro o superiore.
todo.your.list: Lista delle Cose da Fare
todo.status.zero: Clicca sul titolo per Creare l'Articolo!
todo.status.one: L'articolo è stato creato, non pubblicato e ancora in Fase di Lavorazione
todo.status.two: L'articolo è stato pubblicato e ancora in Fase di Lavorazione
todo.status.three: L'articolo è stato completato!
notes: Note
moderation: Moderazione
metadata: Metadati
tags: Tag
article.template: Template Articolo
world: Mondo
category: Categoria
author: Autore
creation.date: Data di Creazione
update.date: Data Ultima Modifica
open: Apri
wip: In Fase di Lavorazione
visibility: Visibilità
public: Pubblico
private: Privato
views: Visualizzazioni
favorites: Preferiti
comments: Commenti
author.notes: Note dell'Autore
access.description: Siamo spiacenti, non hai accesso a questa pagina. Probabilmente
  ciò è dovuto al fatto che l'articolo è privato e non hai i permessi necessari per
  visualizzarlo.
access.return: Torna indietro da dove sei venuto!
access.homepage: Vai alla Homepage
access.passcode: Richiesta Password
access.passcode.description: Questa pagina è protetta da una password! Se possiedi
  la password inseriscila qui sotto per accedere al contenuto.
access.activate: Attivazione Abbonamento
access.activate.description: Scrivi qui sotto il tuo codice di Abbonamento per accedere
  al contenuto. È davvero così semplice!
access.activate.subscription: Attiva Abbonamento
access.activate.code: Inserisci Codice di Attivazione
access.activate.login: Devi aver eseguito l'accesso per attivare il tuo abbonamento!
state: Stato
access.multipass: Multipass?
community: Community
dashboard.worlds.max: Hai raggiunto il numero massimo di Mondi
dashboard.communities: Le Tue Community
dashboard.recent.articles: I tuoi articoli recenti
dashboard.continue: Continua a Costruire
dashboard.worldbuilding.disabled: Le funzionalità di worldbuilding sono disabilitate
dashboard.podcast.cta: Ascolta il nostro Podcast sul Worldbuilding
dashboard.videos: Video Recenti
dashboard.campaigns: Le Tue Campagne
dashboard.characters: I Tuoi Personaggi
dashboard.worlds: I Tuoi Mondi
dashboard.events: Eventi
dashboard.news: Notizie
dashboard.manage.features: Gestisci le funzionalità abilitate
dashboad.cta: INIZIA A COSTRUIRE
dashboard.create.first: Crea il tuo primo Mondo!
publication.date: Data di Pubblicazione
theme: Tema
join.discord.description: Prendi parte allo sviluppo di World Anvil - partecipa alle
  sfide di world building - vinci premi e fantastiche medaglie!
dismiss: Rimuovi
identifier: Identificatore
welcome: Benvenuto
dashboard.upcoming.stream: Stream ed Eventi in Arrivo
dashboard.upcoming.sessions: Sessioni in Arrivo
dashboard.followed.characters: Personaggi Seguiti
dashboard.followed.worlds: I Tuoi Mondi Seguiti
dashboard.help.grow: Aiutaci a mantenere Wold Anvil vivo e in crescita!
dashboard.in.news: Dentro le Notizie
dashboard.dev.updates: Sviluppo Aggiornamenti
dashboard.features.mistake: Hai attivato le funzionalità di worldbuilding per errore?
dashboard.page.title: Il tuo Pannello di Controllo Globale
studio.templates: 'Laboratorio: Template Articoli'
goto.articles.list: Vai alla Lista Articoli
goto.account: Vai ai dettagli Account
join.worldanvil.cta: Unisciti alla Gilda dei Worldbuilder
join.discord: Unisciti al nostro Discord
upcoming.streams: Stream in Arrivo
