status: Visibilitat
notes: Apunts
tags: Etiquetes
world: Món
category: Categoria
author.notes: Notes de l'autor
new: noves
weight: Importància
title: Títol
description: Descripció
help: Ajuda
home: Pàgina d'inici
class: Classe CSS
class.name: Nom de la classe CSS
allies: Aliats i camarades
private.club: Club privat. Només membres del Gremi
world.designer: Tauler de disseny del món
meta.title.standard: Worldbuilding i gestió de campanyes de rol | World Anvil
meta.description.standard: Eines de gestió de worldbuilding i campanyes de rol per
  tots els escriptors, Dungeon Masters i autors de ficció
studio.homepage: Pàgina principal de l'estudi del creador
studio.description.header: Qué és l'estudi del creador
todo.your.list: Coses per fer
todo.status.zero: Cliqueu sobre el títol per crear l'article!
todo.status.one: Aquest article està creat, no publicat i en construcció
todo.status.two: Aquest article està publicat i en construcció
todo.status.three: L'article està acabat!
moderation: Moderació
metadata: Metadades
wip: En construcció
article.template: Plantilla
author: Autor
creation.date: Data de creació
update.date: Data de l'última actualització
visibility: Visibilitat
public: Públic
private: Privat
open: Obert
views: Visites
favorites: Preferits
comments: Comentaris
access.description: Ho sento, però no podeu accedir a aquesta pàgina. Segurament és
  un article privat i no teniu els permisos necessaris per veure'l.
access.return: Torna al lloc d'on venies!
access.homepage: Ves a la pàgina principal
studio.description.text: L'Estudi del creador és la llar de tota la personalització
  avançada a World Anvil. Grandmasters, i rangs superiors, podran crear i compartir
  fitxes de personatge, widgets, marcadors de mapa personalitzats, i molt més a mesura
  que anem creixent.
guild.required: Necessites ser part del Gremi per utilitzar aquesta funció!
guild.required.master: Per poder utilitzar aquesta funció necessites ser, com a mínim,
  Master del Gremi.
guild.required.grandmaster: Per poder utilitzar aquesta funció necessites ser, com
  a mínim, Grandmaster del Gremi.
access.multipass: Multientrada?
studio.pins: 'Estudi del creador: marcadors'
studio.sheets: 'Estudi del creador: fitxes'
access.passcode: Contrasenya obligatòria
access.passcode.description: Aquesta pàgina està protegida amb una contrasenya! Si
  la sabeu, introduïu-la a sota per accedir al contingut.
username: Nom d'usuari
state: Estat
access.activate: Activació de subscripcions
access.activate.description: Escriviu el vostre codi de subscripció a sota per accedir
  al contingut. És així de fàcil!
access.activate.subscription: Activa la subscripció
access.activate.code: Introduïu el codi d'activació
access.activate.login: Cal que inicieu la sessió per activar la vostra subscripció!
identifier: Identificador
studio.templates: 'Estudi del creador: plantilles d''article'
theme: Tema
publication.date: Data de publicacó
welcome: Hola
community: Comunitat
upcoming.streams: Directes futurs
dismiss: Tanca
join.discord: Uniu-vos al nostre Discord
join.discord.description: Col·laboreu en el desenvolupament de World Anvil, participeu
  en competicions de creació de mons, guanyeu premis i medalles!
join.worldanvil.cta: Uniu-vos al Gremi de Worldbuilders
dashboard.page.title: Taulell general
goto.articles.list: Aneu a la llista d'articles
goto.account: Aneu a detalls del compte
dashboard.create.first: Creeu el vostre primer mon!
dashboad.cta: MANS A LA FEINA
dashboard.features.mistake: Heu activat funcions de worldbuilding per error?
dashboard.manage.features: Administreu les vostres funcions activades
dashboard.news: Novetats
dashboard.events: Esdeveniments
dashboard.worlds: Els vostres mons
dashboard.characters: Els vostres personatges
dashboard.campaigns: Les vostres campanyes
dashboard.communities: Les vostres comunitats
dashboard.dev.updates: Novetats de desenvolupament
dashboard.videos: Vídeos recents
dashboard.in.news: Notícies
dashboard.podcast.cta: Escolteu el nostre podcast de worldbuilding
dashboard.worldbuilding.disabled: Les funcions de worldbuilding estan desactivades
dashboard.continue: Continueu escrivint
dashboard.recent.articles: Articles més recents
dashboard.worlds.max: Heu assolit el vostre màxim de mons
dashboard.help.grow: Ajudeu-nos a mantenir i fer créixer World Anvil!
dashboard.upcoming.stream: Propers directes i esdeveniments
dashboard.upcoming.sessions: Properes sessions
dashboard.followed.characters: Personatges que seguiu
dashboard.followed.worlds: Mons que seguiu
dashboard.stream: Propers directes
dashboard.world.memberships: Subscripcions a mons
notifications: Notificacions
advanced_options: Opcions i eines avançades
reference: Referència de les etiquetes de disseny
