new: nuevas
title: Título
status: Visibilidad
help: Ayuda
home: Inicio
allies: Aliados y camaradas
world.designer: Panel del creador
meta.title.standard: Worldbuilding y gestión de campañas de rol | World Anvil
meta.description.standard: Herramientas de gestión para la construcción de mundos
  y campañas de rol para todos los escritores, directores de juego y autores de ficción
description: Descripción
weight: Importancia
private.club: Club privado. Solo miembros del Gremio
class: CSS Class
class.name: CSS Class Name
studio.homepage: Página de inicio del estudio del creador
studio.description.header: Qué es el estudio del creador
studio.description.text: El estudio del creador es el hogar de toda la personalización
  avanzada en World Anvil. Grandmasters y superior podrán crear y compartir fichas
  de personaje, widgets, marcadores de mapa personalizados y mucho más mientras crecemos.
guild.required: ¡Necesitas ser parte del Gremio para utilizar esta funcionalidad!
guild.required.master: Necesitas ser al menos Master del Gremio para poder utilizar
  esta funcionalidad.
guild.required.grandmaster: Necesitas ser al menos Grandmaster del Gremio para poder
  utilizar esta funcionalidad.
todo.your.list: Lista de tareas
todo.status.zero: ¡Haz clic en el título para crear el artículo!
todo.status.one: El artículo está creado, sin publicar y aún en progreso
todo.status.two: El artículo ha sido publicado y aún está en progreso
todo.status.three: ¡El artículo está terminado!
notes: Notas
moderation: Moderación
metadata: Metadatos
article.template: Plantilla
world: Mundo
category: Categoría
author: Autor
creation.date: Fecha de creación
update.date: Última edición
tags: Etiquetas
visibility: Visibilidad
public: Público
private: Privado
open: Abierto
views: Visitas
favorites: Favoritos
comments: Comentarios
wip: En proceso
access.multipass: ¿Multipase?
access.description: Lo siento mucho, pero no tienes acceso a esta página. Probablemente
  el artículo es privado y no tienes los permisos necesarios para verlo.
access.homepage: Ir a la página principal
access.return: ¡Vuelve al lugar de donde has venido!
author.notes: Notas del autor
studio.pins: 'Estudio del creador: pines'
studio.sheets: 'Estudio del creador: fichas'
access.passcode: Contraseña requerida
access.passcode.description: ¡Esta página está protegida con contraseña! Si tienes
  la contraseña, por favor introdúcela abajo para acceder al contenido.
username: Nombre de usuario
state: Estado
access.activate: Activación de la suscripción
access.activate.description: Escribe tu código de suscripción abajo para acceder al
  contenido, ¡así de fácil!
access.activate.subscription: Activar suscripción
access.activate.code: Introducir código de activación
access.activate.login: ¡Tienes que iniciar sesión para activar tu suscripción!
identifier: Identificador
studio.templates: 'Estudio del Creador: plantillas de artículo'
theme: Tema
publication.date: Fecha de publicación
dashboard.upcoming.stream: Próximos eventos y streamings
dashboard.upcoming.sessions: Próximas sesiones
dashboard.followed.characters: Personajes que sigues
dashboard.followed.worlds: Mundos que sigues
dashboard.help.grow: ¡Ayúdanos a seguir haciendo crecer World Anvil!
dashboard.worlds.max: Has alcanzado el número máximo de mundos que puedes crear
dashboard.recent.articles: Tus artículos recientes
dashboard.continue: Sigue creando
dashboard.worldbuilding.disabled: Las funciones de worldbuilding están desactivadas
dashboard.podcast.cta: ¡Escucha nuestro podcast de worldbuilding!
dashboard.videos: Vídeos recientes
dashboard.in.news: Noticias
dashboard.dev.updates: Noticias del desarrollo
dashboard.communities: Tus comunidades
dashboard.campaigns: Tus campañas
dashboard.characters: Tus personajes
dashboard.worlds: Tus mundos
dashboard.events: Eventos
dashboard.news: Novedades
dashboard.manage.features: Ajusta tus funciones activadas
dashboard.features.mistake: ¿Has activado las funciones de worldbuilding por error?
dashboad.cta: CONSTRUYE
dashboard.create.first: ¡Crea tu primer mundo!
dashboard.page.title: Tu panel principal
goto.articles.list: Ir a la lista de artículos
goto.account: Ir a los detalles de la cuenta
join.worldanvil.cta: Únete al Gremio de Worldbuilders
join.discord.description: Participa en el desarrollo de World Anvil, únete a nuestros
  desafíos de worldbuilding, ¡y gana premios y medallas!
join.discord: Únete al Discord
upcoming.streams: Futuras transmisiones
dismiss: Cerrar
welcome: Hola
community: Comunidad
dashboard.stream: Próximos directos
dashboard.world.memberships: Tus suscripciones a mundos
notifications: Notificaciones
advanced_options: Opciones avanzadas
reference: Referencia de las etiquetas del diseño
