new: nieuwe
title: Titel
status: Status
help: Heb je hulp nodig?
allies: Vrienden van WorldAnvil
home: Startpagina
description: Beschrijving
world.designer: Wereld Ontwerpers Paneel
weight: Gewicht
private.club: Privé club. Alleen toegang voor Guild Members
meta.title.standard: Wereldbouwen en RPG Campagne Management | World Anvil
meta.description.standard: Worldbuilding en RPG Campagne Management tools voor elke
  Schrijver en Dungeon Master
studio.description.header: Wat is de Creator’s Studio
studio.description.text: De Creator’s Studio is het middelpunt van alle geavanceerde
  aanpassingen in World Anvil. Grandmasters, en hoger, kunnen Personage sheets, Widgets
  en Aangepaste Markers voor kaarten maken en delen. En nog veel meer in toekomst.
class: CSS Class
class.name: CSS Class naam
studio.homepage: Creator's Studio Homepage
notes: Notities
tags: Tags
world: Wereld
username: Gebruikersnaam
studio.pins: 'Creator''s Studio: Pins'
studio.sheets: 'Creator''s Studio: Sheets'
state: Provincie
guild.required: Deze optie vereist een Guild Membership!
guild.required.master: Deze optie vereist een Guild Membership van Master of hoger.
guild.required.grandmaster: Deze optie vereist een Guild Membership van Grandmaster
  of hoger.
todo.your.list: Taken Lijst
todo.status.zero: Klik op de titel om een Artikel aan te maken!
todo.status.one: Het Artikel is aangemaakt, niet gepubliceerd en nog in bewerking
todo.status.two: Het artikel is Gepubliceerd en is nog steeds in bewerking
todo.status.three: Het artikel is afgewerkt!
metadata: Metagegevens
article.template: Artikel sjabloon
author: Auteur
creation.date: Aanmaakdatum
update.date: Laatste Bijgewerkte Datum
theme: Thema
category: Categorie
publication.date: Publicatie Datum
public: Openbaar
private: Privé
visibility: Zichtbaarheid
open: Open
favorites: Favorieten
comments: Opmerkingen
author.notes: Auteurs notities
access.return: Keer terug van waar je gekomen bent!
access.homepage: Ga naar Hoofdpagina
access.passcode: Wachtwoord vereist
access.passcode.description: Deze pagina is beschermd door een wachtwoord! Indien
  je het wachtwoord kent gelieve het hieronder in te geven om toegang te krijgen tot
  de inhoud.
access.activate: Abonnement Activatie
access.activate.description: Geef je Abonnementscode hieronder in om toegang te krijgen
  tot de inhoud. Het is zo gemakkelijk!
access.activate.subscription: Abonnement Activeren
access.activate.code: Geef Activatie Code in
access.activate.login: Je moet ingelogd zijn om je abonnement te activeren!
views: Keer bekeken
welcome: Welkom
community: Gemeenschap
dismiss: Afwijzen
wip: Onderhanden werk
identifier: Identifieerder
join.worldanvil.cta: 'Kom bij onze Worldbuilders Gilde'
join.discord.description: Neem deel aan de ontwikkeling van World Anvil - doe mee
  aan wereldbouw uitdagingen - win prijzen en geweldige badges!
join.discord: Kom bij onze Discord
upcoming.streams: Aankomende Streams
dashboard.page.title: Jouw Globale Dashboard
access.description: Het spijt me zo, maar je hebt geen toegang tot deze pagina. Dit
  komt waarschijnlijk omdat het artikel privé is en u niet over de benodigde rechten
  beschikt om het te bekijken.
moderation: Beheren
goto.articles.list: Ga naar Artikel Lijst
goto.account: Ga naar Account details
dashboard.manage.features: Beheer je geactiveerde functies
dashboard.features.mistake: Heb je per ongeluk functies voor het bouwen van een wereld
  geactiveerd?
dashboad.cta: GA WERELDBOUWEN
dashboard.create.first: Creëer je eerste Wereld!
dashboard.events: Gebeurtenissen
dashboard.news: Nieuws
dashboard.campaigns: Jouw Campagnes
dashboard.characters: Jouw Karakters
dashboard.worlds: Jouw Werelden
dashboard.upcoming.stream: Aankomende Streams & Evenementen
dashboard.upcoming.sessions: Aankomende Sessies
dashboard.followed.characters: Gevolgde Karakters
dashboard.followed.worlds: Jouw Gevolgde Werelden
dashboard.help.grow: Help ons World Anvil levend en groeiend te houden!
dashboard.worlds.max: Je hebt de maximale nummer aan Werelden bereikt
dashboard.recent.articles: 'Jouw Recente artikelen'
dashboard.continue: Ga door met Bouwen
dashboard.worldbuilding.disabled: De wereldbouwers functies zijn uitgeschakeld
dashboard.podcast.cta: Luister naar onze Wereldbouwers Podcast
dashboard.videos: "Recente Video's"
dashboard.in.news: In de Nieuws
dashboard.dev.updates: Ontwikkelingsupdates
dashboard.communities: Jouw Community's
access.multipass: Multipass?
studio.templates: "Creator's Studio: Artikel Sjablonen"
dashboard.stream: Aankomende Streams
notifications: Notificaties
dashboard.world.memberships: Wereld Lidmaatschappen
reference: Ontwerp Label Refarenties
