new: nova(s)
title: Título
status: Status
help: Precisa de Ajuda?
home: Início
allies: Aliados e Parceiros no Crime
world.designer: Painel do Criador de Mundos
meta.title.standard: Worldbuilding e Administração de Campanhas de RPG | World Anvil
meta.description.standard: Ferramenta de Worldbuilding e Administração de Campanhas
  de RPG para Contadores de Histórias, Mestres de RPG e Escritores de Ficção
description: Descrição
weight: Peso
private.club: Clube privado. Apenas Membros da Guilda
class: Classe de CSS
class.name: Nome da Classe de CSS
studio.homepage: Página Inicial do Estúdio do Criador
studio.description.header: O que é o Estúdio do Criador
studio.description.text: O Estúdio do Criador é o lar de todas as customizações avançadas
  no World Anvil. Doadores do nível "Grandmaster" e acima serão capazes de criar e
  compartilhar Fichas de Personagem, Widgets, Marcadores de Mapa Personalizados e
  muito mais conforme crescemos.
guild.required: Esta funcionalidade requer que você seja membro da Guilda!
guild.required.master: Esta funcionalidade requer que você seja um membro da Guilda
  nível Mestre ou maior.
guild.required.grandmaster: Esta funcionalidade requer que você seja um membro da
  Guilda nível Grão-mestre ou maior.
todo.your.list: Lista de afazeres
todo.status.zero: Clique no título para Criar o Artigo!
todo.status.one: O artigo foi criado, não foi publicado e ainda está em fase de construção
tags: Tags
article.template: Modelo de artigo
todo.status.two: O Artigo foi publicado e ainda está em fase de construção
todo.status.three: O Artigo está terminado!
moderation: Moderação
metadata: Metadados
author: Autor
creation.date: Data de criação
update.date: Última atualização
notes: Anotações
world: Mundo
category: Categoria
access.multipass: Passe Múltiplo?
access.description: Sinto muito mas você não tem acesso a essa página. Isso provavelmente
  se deve ao fato do artigo ser privado e você não ter as permissões necessárias para
  visualizá-lo.
access.return: Volte por onde você veio!
access.homepage: Ir para a Página Inicial
visibility: Visibilidade
public: Público
private: Privado
open: Aberto
views: Visualizações
favorites: Gostaram
comments: Comentários
wip: Em fase de construção
author.notes: Notas do Autor
studio.pins: 'Estúdio do Criador: Marcações'
studio.sheets: 'Estúdio do Criador: Fichas'
access.passcode: Senha Necessária
access.passcode.description: Esta página é protegida por senha! Se você tem a senha,
  favor insira-a abaixo para acessar o conteúdo.
username: Nome de Usuário
state: Estado
access.activate: Ativação de Inscrição
access.activate.code: Digite o Código de Ativação
access.activate.description: Escreva abaixo seu código de Inscrição para ter acesso
  ao conteúdo. É simples assim!
access.activate.subscription: Ativar Inscrição
access.activate.login: Você deve estar logado para ativar sua inscrição!
dismiss: Dispensar
welcome: Bem-vindo(a)
community: Comunidade
notifications: Notificações
