new: nouveau
title: Titre
status: Statut
help: Aide
home: Accueil
description: Description
allies: Partenaires
world.designer: Concepteur de monde
meta.title.standard: Concepteur de mondes et de campagnes de JDR | World Anvil
meta.description.standard: 'Outils de conception de mondes et de campagnes de JDR
  pour tous : Auteurs, Maîtres de Jeu, Conteurs...'
weight: Poids
private.club: Club privé. Membres de la Guilde des Forgemondes uniquement
class: Classe CSS
class.name: Nom de classe CSS
studio.homepage: Accueil de la Forge du Créateur
studio.description.header: Qu'est ce que la Forge du Créateur
studio.description.text: La Forge du Créateur est l'atelier de personnalisation avancée
  de WorldAnvil. Grand maîtres et rangs supérieurs pourront créer et partager divers
  contenus tel que des fiches personnages, des gadgets, des indicateurs personnalisés
  pour cartes et bien plus.
guild.required: Cette fonctionnalité nécessite une souscription à la guilde des Forgemondes!
todo.your.list: Liste 'À faire'
todo.status.zero: Cliquez sur le titre pour créer l'article.
todo.status.three: L'article est fini.
notes: Notes
tags: Mots-clés
article.template: Template d'article
world: Monde
category: Catégorie
author: Auteur
creation.date: Date de Création
update.date: Dernière mise à jour
private: Privé
favorites: Favoris
comments: Commentaires
author.notes: Notes d'auteur
access.description: Vous n'avez pas accès à cette page. Cet article est probablement
  privé et vous n'avez pas les droits nécessaires pour le voir.
access.return: Retournez d'où vous venez !
username: Nom d'utilisateur
state: État
studio.pins: 'Forge du Créateur : Épingles'
studio.sheets: 'Forge du créateur : Fiches'
guild.required.master: Cette fonctionnalité requiert un abonnement Maître ou supérieur
  de la Guilde des Forgemondes.
guild.required.grandmaster: Cette fonctionnalité requiert un abonnement Grand Maître
  ou supérieur de la Guilde des Forgemondes.
todo.status.one: L'article est créé, Non Publié et toujours Inachevé
todo.status.two: L'article est Publié mais toujours Inachevé
moderation: Modération
metadata: Métadonnées
visibility: Visibilité
public: Public
open: Ouvert
views: Vues
wip: Inachevé
access.multipass: Multipass ?
access.homepage: Aller à la Page d'Accueil
access.passcode: Mot de passe Requis
access.passcode.description: Cette page est protégée par un mot de passe ! Si vous
  l'avez, entrez le dessous pour accéder au contenu.
access.activate: Activation d'Abonnement
access.activate.description: Saisissez votre code d'Abonnement ci-dessous pour accéder
  au contenu. C'est aussi simple que ça !
access.activate.subscription: Activer Abonnement
access.activate.code: Entrer Code d'Activation
access.activate.login: Vous devez être connecté pour activer votre abonnement !
